### ISSUE TITLE
Test public pre-release version of Safari

### ISSUE THREAD

**Issue by jeffcarp** [w3c/wptdashboard#110] opened 2017-08-31 17:38 UTC
We currently test the latest version of Safari on Sauce Labs, which is not a pre-release version. We should be testing against [Safari Technology Preview](https://developer.apple.com/safari/technology-preview/).

**Comment by foolip** [comment] 2017-09-27 22:15
Treating this as a dupe of https://github.com/w3c/wptdashboard/issues/112 which has more discussion.

**Closed by foolip** 2017-09-27 22:15 UTC
Labels: running
