### ISSUE TITLE
Why is "Test file" shown in results?

### ISSUE THREAD

**Issue by foolip** [w3c/wptdashboard#129] opened 2017-09-30 20:12 UTC
In http://wpt.fyi/speech-api/historical.html there is a "Test file" column with passes. But this is not one of the tests, see https://w3c-test.org/speech-api/historical.html.

Is this to convey that there wasn't a harness error?

**Comment by foolip** [comment] 2017-09-30 20:45
Looks like it is the harness status. I'd suggest two changes:
* Renaming to "Harness status" to match what the default testharnessreport.js says
* Never counting this as part of the test results. Currently it appears to be counted as a test among others.

**Comment by gsnedders** [comment] 2017-09-30 22:26
> Never counting this as part of the test results. Currently it appears to be counted as a test among others.

We probably want to just ignore all subtest results if we have a harness error.

**Comment by foolip** [comment] 2017-10-01 07:09
Wouldn't that be excessive? It's still possible that some of the tests have run correctly and have valid results, right? If there are some harness errors that aren't trivial to fix, then we might end up holding the whole file hostage for some engine, and they'll be unimpressed.

**Comment by jgraham** [comment] 2017-10-01 18:35
Note that reftests only have a test file result since they don't use the subtest concept.

I think that conceptually separating the harness status out for test types which use subtests makes sense, but I'm not sure what the exact best apporach is. Certainly ignoring the subtest results unless the harness status is OK would be bad; I'm pretty sure there are hundreds of cases where e.g. one subtest gets results and another times out causing an overall status of timeout, but stable behaviour.

Ideally I would like the directory-level summaries to say something like `100/150 tests completed; 12345/19000 subtests passed`, since I think that would make it clearer why the number of subtest results can differ between browsers.

**Comment by foolip** [comment] 2017-10-01 18:41
@bobholt @drufball, see @jgraham's comment above, may be relevant to defining metrics.

**Comment by lukebjerring** [comment] 2017-11-28 20:14
This is a duplicate of https://github.com/w3c/wptdashboard/issues/92

**Closed** 2017-12-05 20:32 UTC
