### ISSUE TITLE
Directories have links to themselves within that don't work (can't drill down)

### ISSUE THREAD

**Issue by foolip** [w3c/wptdashboard#350] opened 2018-01-12 20:03 UTC
https://wpt.fyi/html now looks like this:
<img width="823" alt="screen shot 2018-01-12 at 9 01 21 pm" src="https://user-images.githubusercontent.com/498917/34893032-c5812284-f7db-11e7-887d-11ceda738182.png">

https://wpt.fyi/html/dom (which I knew existed) instead looks like this:
<img width="820" alt="screen shot 2018-01-12 at 9 02 24 pm" src="https://user-images.githubusercontent.com/498917/34893072-e8f36fb0-f7db-11e7-94a9-efce7e22b76b.png">

I don't know what the numbers mean here, but there is no html/ directory there, but are other directories:
https://github.com/w3c/web-platform-tests/tree/master/html/dom

This makes wpt.fyi currently unusable.

**Comment by mattl** [comment] 2018-01-12 20:04
Do we have a sense of when this *was* working?

**Comment by foolip** [comment] 2018-01-12 20:05
It was working when I filed https://github.com/w3c/wptdashboard/issues/344

**Comment by rwaldron** [comment] 2018-01-12 20:34
@foolip I've reverted f39dbaa5c4585fd02da86ceea1a5039156acb0a5 for now, since that was the most likely candidate for introducing site facing issues.

**Comment by rwaldron** [comment] 2018-01-12 21:23
@foolip I determined the cause of the issue, and opened a PR with webcomponents fixups _and_ a commit that fixes the regression.

**Comment by boazsender** [comment] 2018-01-12 22:23
This was resolved by #351.

**Comment by foolip** [comment] 2018-01-12 23:19
Thanks for the speedy fix everyone!

**Closed** 2018-01-22 16:13 UTC
Labels: bug, priority:urgent
